spring.application.name=DuAnTrainning
server.port= 8080

# DATABASE CONFIGURATION
spring.datasource.url=jdbc:postgresql://localhost:5432/auction_system
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / HIBERNATE CONFIGURATION

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# IMAGE UPLOAD
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=100MB

# CLOUDINARY
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dmyrfnxfv}
cloudinary.api-key=${CLOUDINARY_API_KEY:567893817722166}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:UXEZV0sENuJ1caxccS8P9H2dbCU}

