spring.application.name=DuAnTrainning
server.port=${PORT:8080}

# DATABASE CONFIGURATION
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/auction_system}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / HIBERNATE CONFIGURATION

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# IMAGE UPLOAD
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=100MB

# CLOUDINARY :
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dmyrfnxfv}
cloudinary.api-key=${CLOUDINARY_API_KEY:567893817722166}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:UXEZV0sENuJ1caxccS8P9H2dbCU}

# JACKSON CONFIGURATION (SNAKE_CASE)
spring.jackson.property-naming-strategy=SNAKE_CASE

# ===================================================================
# INTERNATIONALIZATION (i18n) CONFIGURATION
# ===================================================================
# Đường dẫn tên file gốc (Spring sẽ tự quét messages_vi.properties, messages_en.properties...)
spring.messages.basename=messages

# Ép kiểu đọc file UTF-8 để hiển thị chuẩn Tiếng Việt có dấu
spring.messages.encoding=UTF-8

# Ngôn ngữ mặc định của ứng dụng khi Client không gửi Header Accept-Language
spring.web.locale=vi

# Định hướng cho Spring Boot sử dụng Header Accept-Language từ HTTP Request
spring.web.locale-resolver=accept_header

# REDIS CACHING CONFIGURATION
spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}
spring.data.redis.password=${SPRING_REDIS_PASSWORD:}
spring.data.redis.timeout=3000ms


