server.port=8082
spring.application.name=PAYMENT-SERVICE

# CSDL PostgreSQL cho Dịch vụ Ví Tiền Ảo
spring.datasource.url=jdbc:postgresql://localhost:5432/payment_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jackson.property-naming-strategy=SNAKE_CASE

# Đăng ký Service Discovery với Eureka Server (Port 8761)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Secret key bí mật cho giao tiếp nội bộ giữa các microservices (Server-to-Server)
app.internal.service-key=${INTERNAL_SERVICE_KEY:AuctionPaymentInternalSecretKey2026!@#}