server.port=8761
spring.application.name=EUREKA-SERVER

eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/

# Tắt Self-Preservation trong môi trường Dev để hủy ngay service khi đứt kết nối
eureka.server.enable-self-preservation=false
